package com.wbhhc.domain;

// Generated 2013-12-22 21:08:55 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sysdept generated by hbm2java
 */
@Entity
@Table(name = "SYSDEPT")
public class Sysdept implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private Set<Sysuser> sysusers = new HashSet<Sysuser>(0);

	public Sysdept() {
	}

	public Sysdept(BigDecimal id) {
		this.id = id;
	}

	public Sysdept(BigDecimal id, String name, Set<Sysuser> sysusers) {
		this.id = id;
		this.name = name;
		this.sysusers = sysusers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysdept")
	public Set<Sysuser> getSysusers() {
		return this.sysusers;
	}

	public void setSysusers(Set<Sysuser> sysusers) {
		this.sysusers = sysusers;
	}

}
