package com.wbhhc.domain;

// Generated 2013-12-22 21:08:55 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sysoperate generated by hbm2java
 */
@Entity
@Table(name = "SYSOPERATE")
public class Sysoperate implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String code;
	private Set<Sysrolepageopt> sysrolepageopts = new HashSet<Sysrolepageopt>(0);
	private Set<Syspage> syspages = new HashSet<Syspage>(0);

	public Sysoperate() {
	}

	public Sysoperate(BigDecimal id) {
		this.id = id;
	}

	public Sysoperate(BigDecimal id, String name, String code,
			Set<Sysrolepageopt> sysrolepageopts, Set<Syspage> syspages) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.sysrolepageopts = sysrolepageopts;
		this.syspages = syspages;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysoperate")
	public Set<Sysrolepageopt> getSysrolepageopts() {
		return this.sysrolepageopts;
	}

	public void setSysrolepageopts(Set<Sysrolepageopt> sysrolepageopts) {
		this.sysrolepageopts = sysrolepageopts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SYSPAGEANDOPT", joinColumns = { @JoinColumn(name = "OPTID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "PAGEID", nullable = false, updatable = false) })
	public Set<Syspage> getSyspages() {
		return this.syspages;
	}

	public void setSyspages(Set<Syspage> syspages) {
		this.syspages = syspages;
	}

}
