package com.wbhhc.domain;

// Generated 2013-12-22 21:08:55 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sysrolepageopt generated by hbm2java
 */
@Entity
@Table(name = "SYSROLEPAGEOPT")
public class Sysrolepageopt implements java.io.Serializable {

	private BigDecimal id;
	private Sysrole sysrole;
	private Sysoperate sysoperate;
	private Syspage syspage;

	public Sysrolepageopt() {
	}

	public Sysrolepageopt(BigDecimal id, Sysrole sysrole,
			Sysoperate sysoperate, Syspage syspage) {
		this.id = id;
		this.sysrole = sysrole;
		this.sysoperate = sysoperate;
		this.syspage = syspage;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLEID", nullable = false)
	public Sysrole getSysrole() {
		return this.sysrole;
	}

	public void setSysrole(Sysrole sysrole) {
		this.sysrole = sysrole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPTID", nullable = false)
	public Sysoperate getSysoperate() {
		return this.sysoperate;
	}

	public void setSysoperate(Sysoperate sysoperate) {
		this.sysoperate = sysoperate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAGEID", nullable = false)
	public Syspage getSyspage() {
		return this.syspage;
	}

	public void setSyspage(Syspage syspage) {
		this.syspage = syspage;
	}

}
