package com.wbhhc.domain;

// Generated 2013-12-22 21:08:55 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sysrole generated by hbm2java
 */
@Entity
@Table(name = "SYSROLE")
public class Sysrole implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private Set<Sysuser> sysusers = new HashSet<Sysuser>(0);
	private Set<Syspage> syspages = new HashSet<Syspage>(0);
	private Set<Sysrolepageopt> sysrolepageopts = new HashSet<Sysrolepageopt>(0);

	public Sysrole() {
	}

	public Sysrole(BigDecimal id) {
		this.id = id;
	}

	public Sysrole(BigDecimal id, String name, Set<Sysuser> sysusers,
			Set<Syspage> syspages, Set<Sysrolepageopt> sysrolepageopts) {
		this.id = id;
		this.name = name;
		this.sysusers = sysusers;
		this.syspages = syspages;
		this.sysrolepageopts = sysrolepageopts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SYSUSERANDROLE", joinColumns = { @JoinColumn(name = "ROLEID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "USERID", nullable = false, updatable = false) })
	public Set<Sysuser> getSysusers() {
		return this.sysusers;
	}

	public void setSysusers(Set<Sysuser> sysusers) {
		this.sysusers = sysusers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SYSROLEANDPAGE", joinColumns = { @JoinColumn(name = "ROLEID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "PAGEID", nullable = false, updatable = false) })
	public Set<Syspage> getSyspages() {
		return this.syspages;
	}

	public void setSyspages(Set<Syspage> syspages) {
		this.syspages = syspages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysrole")
	public Set<Sysrolepageopt> getSysrolepageopts() {
		return this.sysrolepageopts;
	}

	public void setSysrolepageopts(Set<Sysrolepageopt> sysrolepageopts) {
		this.sysrolepageopts = sysrolepageopts;
	}

}
