package com.wbhhc.domain;

// Generated 2013-12-22 21:08:55 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sysuser generated by hbm2java
 */
@Entity
@Table(name = "SYSUSER")
public class Sysuser implements java.io.Serializable {

	private BigDecimal id;
	private Sysdept sysdept;
	private String name;
	private String loginname;
	private String password;
	private Set<Sysrole> sysroles = new HashSet<Sysrole>(0);

	public Sysuser() {
	}

	public Sysuser(BigDecimal id, Sysdept sysdept) {
		this.id = id;
		this.sysdept = sysdept;
	}

	public Sysuser(BigDecimal id, Sysdept sysdept, String name,
			String loginname, String password, Set<Sysrole> sysroles) {
		this.id = id;
		this.sysdept = sysdept;
		this.name = name;
		this.loginname = loginname;
		this.password = password;
		this.sysroles = sysroles;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPTID", nullable = false)
	public Sysdept getSysdept() {
		return this.sysdept;
	}

	public void setSysdept(Sysdept sysdept) {
		this.sysdept = sysdept;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LOGINNAME", length = 100)
	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	@Column(name = "PASSWORD", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SYSUSERANDROLE", joinColumns = { @JoinColumn(name = "USERID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ROLEID", nullable = false, updatable = false) })
	public Set<Sysrole> getSysroles() {
		return this.sysroles;
	}

	public void setSysroles(Set<Sysrole> sysroles) {
		this.sysroles = sysroles;
	}

}
